name: gym_app
description: This is a project of a new Excercise App.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  supabase_flutter: 2.8.4
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.0.15
  image_picker: 1.1.2
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

