name: gym_app
description: This is a project of a new Excercise App.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  supabase_flutter: 2.8.4
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.0.15
  image_picker: 1.1.2
  permission_handler: ^10.4.3
  path_provider: ^2.1.5
  http: ^1.3.0
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo_gymbly_v2.png"

flutter_native_splash:
  color: "#1ABC9C"
  image: "lib/assets/logo_gymbly_v2_letra.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

